# Generated by Django 5.0.3 on 2024-04-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='follow_author',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
